### ISSUE TITLE
Planetary Rings

### ISSUE THREAD

**Issue by Quenten2811** [kurt1288/MapToGlobe#1]
I like very much the addition of a moon and planetary rings in the beta edition. However, the rings seem to circle the poles, rather than the equator. Can this be fixed please? Also, can you add the option to having more than 1 moon?

**Comment by kurt1288** [comment]
I'm not sure if you're actually seeing an issue, as I don't see any problem when I add rings. When you add rings, you can show controls that lets you reposition them. The pivot point should still be the center and not the pole(s). Let me know if this is not the behavior you're seeing.
